### ISSUE TITLE
requests.timestamp_day cannot be converted to default timezone

### ISSUE THREAD

**Issue by robert-carroll** [ccsd/canvas-data-embulk-configs#4]
This field can't be converted to a local default timezone from UTC without a timestamp.
The field is stored in VARCHAR which makes some queries using this field problematic.
You can store the field using Embulk Output SQL type 'date', but there will be no conversion.

Best solution would be to load the table to staging and convert that value in production locally...
or just use timestamp and convert to create a new value from timestamp.

Example: https://github.com/ccsd/canvas-data-embulk-configs/issues/4#issuecomment-565608140

**Comment by lafent** [comment]
Can this be accomplished via an existing embulk filter plugin?  I'm not sure what plugins anyone is using, but I've got a couple I've used for importing some pretty messy data.  I'm about 90% sure I've got one timestamp field that's partially parsed from character data.  I'll take a whack at it.  I'm not sure that's really a viable option for everyone, but I can document it as an option at least -- assuming it actually works like I remember.

**Comment by lafent** [comment]
I've played around with this a little bit and I'm not sure I really understand what the problem is.

My current config for the `requests` data is (MySQL-centric, irrelevant bits removed)

``` 
in:
    parser:
        columns:
        - {name: timestamp, type: timestamp, format: '%Y-%m-%d %H:%M:%S.%L'}
out:
    default_timezone: 'America/Chicago'
    column_options:
        timestamp: {type: 'DATETIME NULL', value_type: timestamp, timestamp_format: '%Y-%m-%d %H:%M:%S.%L'}
```

This gets me the timestamp in my local time.  I haven't cross-checked vs. daylight savings and I do have some other plugins installed.  I don't think anything is mutating the workflow, but I haven't tried to run a vanilla instance either.
